version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-registry-yarnpkg-com:
    type: npm-registry
    url: https://registry.yarnpkg.com
    token: "${{secrets.NPM_REGISTRY_REGISTRY_YARNPKG_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  ignore:
  - dependency-name: titleize
    versions:
    - 2.1.0
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-registry-yarnpkg-com
